version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
